Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

1. Definitions.

   "License" shall mean the terms and conditions for use, reproduction,
   and distribution as defined by Sections 1 through 9 of this document.

   "Licensor" shall mean the copyright owner or entity authorized by
   the copyright owner that is granting the License.

   "Legal Entity" shall mean the union of the acting entity and all
   other entities that control, are controlled by, or are under common
   control with that entity. For the purposes of this definition,
   "control" means (i) the power, direct or indirect, to cause the
   direction or management of such entity, whether by contract or
   otherwise, or (ii) ownership of fifty percent (50%) or more of the
   outstanding shares, or (iii) beneficial ownership of such entity.

   "You" (or "Your") shall mean an individual or Legal Entity
   exercising permissions granted by this License.

2. Grant of License.

   Subject to the terms and conditions of this License, Licensor hereby
   grants You a worldwide, royalty-free, non-exclusive, perpetual,
   irrevocable license to use, reproduce, modify, publish, distribute,
   sublicense, and/or sell copies of the Work.

3. Conditions and Limitations.

   A. Redistributions of the Work must include a copy of this License;
      any other licenses granted by Licensor must be noted in the
      redistributed files.

   B. If You modify the Work, You must include a notice indicating the
      nature of the modifications and the date of any changes.

   C. You must cause any modified files to carry prominent notices
      stating that You changed the files.

   D. You must retain, in the source form of any derivative works that
      You distribute, all copyright, patent, trademark, and attribution
      notices from the source form of the Work, excluding those notices
      that do not pertain to any part of the derivative works.

   E. If the Work includes a "NOTICE" text file as part of its
      distribution, then any Derivative Works that You distribute must
      include a readable copy of the attribution notices contained
      within such NOTICE file, excluding those notices that do not
      pertain to any part of the Derivative Works, in at least one of
      the following places: within a NOTICE text file distributed
      as part of the Derivative Works; within the Source form or
      documentation, if provided along with the Derivative Works; or,
      within a display generated by the Derivative Works, if and
      wherever such third-party notices normally appear. The contents
      of the NOTICE file are for informational purposes only and
      do not modify the License. You may add Your own attribution
      notices within Derivative Works that You distribute, alongside
      or as an addendum to the NOTICE text from the Work, provided
      that such additional attribution notices cannot be construed
      as modifying the License.

   F. You may not use the Work in any way that would be contrary to
      the intentions of the Licensor or to applicable law.

4. Disclaimer of Warranties.

   Unless required by applicable law or agreed to in writing, Licensor
   provides the Work (and each Contributor provides its Contributions)
   on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
   either express or implied, including, without limitation, any warranties