
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\admin\Downloads\Projects\GUI\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("314x555")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 555,
    width = 314,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    1.0,
    1.0,
    313.1875,
    556.0,
    fill="#D9D9D9",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    156.49749755859375,
    95.70763397216797,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=69.3041296005249,
    y=80.4833984375,
    width=174.3867359161377,
    height=28.448471069335938
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_1.place(
    x=113.0391845703125,
    y=261.513427734375,
    width=86.91656494140625,
    height=28.78765869140625
)

canvas.create_text(
    115.8072509765625,
    60.0,
    anchor="nw",
    text="Phone Number",
    fill="#404921",
    font=("Inter", 11 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_2.place(
    x=72.6256103515625,
    y=122.5577392578125,
    width=52.039215087890625,
    height=33.216522216796875
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_3.place(
    x=130.7547607421875,
    y=122.5577392578125,
    width=51.85015869140625,
    height=33.216522216796875
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_4.place(
    x=188.883544921875,
    y=123.111328125,
    width=51.85015869140625,
    height=33.216522216796875
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,background="#D9D9D9",
    command=lambda: print("button_5 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_5.place(
    x=72.6256103515625,
    y=163.5247802734375,
    width=51.850189208984375,
    height=33.216522216796875
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_6.place(
    x=130.7547607421875,
    y=166.2928466796875,
    width=51.85015869140625,
    height=33.216522216796875
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_7.place(
    x=188.883544921875,
    y=166.846435546875,
    width=51.85015869140625,
    height=33.216522216796875
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_8.place(
    x=188.883544921875,
    y=213.349609375,
    width=51.85015869140625,
    height=33.216522216796875
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_9.place(
    x=130.7547607421875,
    y=212.7960205078125,
    width=51.85015869140625,
    height=33.216522216796875
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_10.place(
    x=72.6256103515625,
    y=212.7960205078125,
    width=51.850189208984375,
    height=33.216522216796875
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    157.0,
    25.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    308.0,
    314.0,
    555.1199951171875,
    outline="")

button_image_11 = PhotoImage(
    file=relative_to_assets("goback.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat",bg="#D9D9D9"
)
button_11.place(
    x=11.0,
    y=9.0,
    width=47.0,
    height=23.0
)
window.resizable(False, False)
window.mainloop()
